apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31685
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer

